#!/bin/sh

$EDITOR ~/.dump/runner.sh                                                                                                                                                                     
id_container=`sudo docker inspect jsxopensuse | grep "Id" | cut -c 23-34`                                                                                                                            
sudo docker build --build-arg packages="`cat ~/.jsxopensuse/packages`" --tag=jsxopensuse ~/.jsxopensuse
sudo docker rmi -f $id_container
