#!/bin/bash

nano ~/.jsxopensuse/packages
if [[ "$@" == "--update" ]]
then
	sudo docker build --no-cache=true --build-arg packages="`cat ~/.jsxopensuse/packages`" --tag=jsxopensuse ~/.jsxopensuse/
fi
